version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      commands:
        - pip install -r /Project/requirements.txt

  pre_build:
    commands:
      - echo "Running pre-build commands..."

  build:
    commands:
      - echo "Running build commands..."
      - pytest /Project/test_calculator.py

artifacts:
  files: /Project/test_calculator.py