version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r /Projects/requirements.txt

  pre_build:
    commands:
      - echo "Running pre-build commands..."

  build:
    commands:
      - echo "Running build commands..."
      - pytest /Projects/test_calculator.py

artifacts:
  files: /Projects/test_calculator.py